version: '3.4'

services:
 
  arcoda.bookmark:
    container_name: arcoda-bookmark
    image: arcoda-bookmark:rc1
    build: 
      context: . 
      dockerfile: Services/Api.BookMark/Dockerfile
    env_file:
      - common.env
    ports:
      - 5001:80
    networks:
      - services-network
    
  arcoda.musicstore:
    container_name: arcoda-musicstore
    image: arcoda-musicstore:rc1
    build:
      context: . 
      dockerfile: Services/Api.MusicStore/Dockerfile
    env_file:
      - common.env
    ports:
      - 5002:80
    networks:
      - services-network
             
  arcoda.gateway:
    container_name: arcoda-gateway
    image: arcoda-gateway:rc1
    build:
      context: .
      dockerfile: Api.Gateway/Dockerfile
    env_file:
      - common.env
    ports:
      - 9000:80
    networks:
      - services-network
    depends_on: 
      - arcoda.bookmark
      - arcoda.musicstore
       
networks:
  services-network:
    external: true