apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  labels:
    app: pg
data:
  POSTGRES_DB: admin
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  #DB_HOST: pg

  # psql -h localhost -U postgresadmin --password -p 5444 postgresdb
  # psql -h localhost -U postgresadmin -p 5444 postgres