apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-deploy
  labels:
    app: bookmark-app
  annotations:
spec:
  selector:
    matchLabels:
      app: bookmark-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bookmark-app
    spec:
      containers:
      - name: bookmark-app
        image: arcoda-bookmark:rc1  
        env:
        - name: DB_NAME
          value: bookmark
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: pg-config 