apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicstore-deploy
  labels:
    app: musicstore-app
  annotations:
spec:
  selector:
    matchLabels:
      app: musicstore-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: musicstore-app
    spec:
      containers:
      - name: musicstore-app
        image: arcoda-musicstore:rc1  
        envFrom:
          - configMapRef:
              name: arcoda-config
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: arcoda-config 