apiVersion: v1
kind: Service
metadata:
  name: clienthub-service
  labels:
    app: clienthub-app
spec:
  type: ClusterIP
  selector:
    app: clienthub-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80