apiVersion: v1
kind: Service
metadata:
  name: musicstore-service
  labels:
    app: musicstore-app
spec:
  type: ClusterIP
  selector:
    app: musicstore-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000