apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  secret.json: |-
    {
      "api_key" : "somesecretgoeshere",
      "POSTGRES_USER": "admin",
      "POSTGRES_PASSWORD": "admin",
      "POSTGRES_DB": "admin",
      "DB_USER": "admin",
      "DB_PASSWORD": "admin",
      "DB_NAME": "admin",
      "DB_PORT": 5432
    }